import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes.js';
import { userRouter } from '../modules/users/user.routes.js';
import { warehouseRouter } from '../modules/warehouses/warehouse.routes.js';
import { productRouter } from '../modules/products/product.routes.js';
import { inventoryRouter } from '../modules/inventory/inventory.routes.js';
import { supplierRouter } from '../modules/suppliers/supplier.routes.js';
import { purchaseRouter } from '../modules/purchases/purchase.routes.js';
import { writeOffRouter } from '../modules/write-offs/write-off.routes.js';
import { stockMovementRouter } from '../modules/stock-movements/stock-movement.routes.js';
import { inventarizationRouter } from '../modules/inventarizations/inventarization.routes.js';
import { notificationRouter } from '../modules/notifications/notification.routes.js';
import { reportRouter } from '../modules/reports/report.routes.js';
import { receiptRouter } from '../modules/receipts/receipt.routes.js';
import { companyRouter } from '../modules/companies/company.routes.js';
import { analyticsRouter } from '../modules/analytics/analytics.routes.js';
import { localEventRouter } from '../modules/local-events/local-event.routes.js';
import { billingRouter } from '../modules/billing/billing.routes.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/companies', companyRouter);
apiRouter.use('/billing', billingRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/local-events', localEventRouter);
apiRouter.use('/warehouses', warehouseRouter);
apiRouter.use('/products', productRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/suppliers', supplierRouter);
apiRouter.use('/purchases', purchaseRouter);
apiRouter.use('/write-offs', writeOffRouter);
apiRouter.use('/stock-movements', stockMovementRouter);
apiRouter.use('/inventarizations', inventarizationRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/reports', reportRouter);
apiRouter.use('/receipts', receiptRouter);
