import { Types } from 'mongoose';
import { SessionModel, type SessionDocument } from './session.model.js';

interface CreateSessionInput {
  id: string;
  userId: string;
  refreshTokenHash: string;
  userAgent?: string | null;
  ipAddress?: string | null;
  expiresAt: Date;
}

export const sessionRepository = {
  /** Explicit _id is pre-generated by the caller so it can be embedded in the JWT before the row exists. */
  async create(input: CreateSessionInput): Promise<SessionDocument> {
    return SessionModel.create({
      _id: new Types.ObjectId(input.id),
      userId: input.userId,
      refreshTokenHash: input.refreshTokenHash,
      userAgent: input.userAgent ?? null,
      ipAddress: input.ipAddress ?? null,
      expiresAt: input.expiresAt,
    });
  },

  /** Includes refreshTokenHash - only for refresh-token verification. */
  async findByIdAndUserWithHash(id: string, userId: string): Promise<SessionDocument | null> {
    if (!Types.ObjectId.isValid(id)) return null;
    return SessionModel.findOne({ _id: id, userId }).select('+refreshTokenHash').exec();
  },

  async findByIdAndUser(id: string, userId: string): Promise<SessionDocument | null> {
    if (!Types.ObjectId.isValid(id)) return null;
    return SessionModel.findOne({ _id: id, userId }).exec();
  },

  async findAllByUser(userId: string): Promise<SessionDocument[]> {
    return SessionModel.find({ userId }).sort({ lastUsedAt: -1 }).exec();
  },

  async updateHash(id: string, refreshTokenHash: string, expiresAt: Date): Promise<void> {
    await SessionModel.updateOne(
      { _id: id },
      { $set: { refreshTokenHash, expiresAt, lastUsedAt: new Date() } },
    ).exec();
  },

  async deleteById(id: string): Promise<void> {
    if (!Types.ObjectId.isValid(id)) return;
    await SessionModel.deleteOne({ _id: id }).exec();
  },

  async deleteByIdAndUser(id: string, userId: string): Promise<boolean> {
    if (!Types.ObjectId.isValid(id)) return false;
    const result = await SessionModel.deleteOne({ _id: id, userId }).exec();
    return result.deletedCount > 0;
  },

  async deleteAllByUser(userId: string): Promise<void> {
    await SessionModel.deleteMany({ userId }).exec();
  },
};
