import { Types } from 'mongoose';
import { PlatformAdminSessionModel, type PlatformAdminSessionDocument } from './admin-session.model.js';

interface CreateAdminSessionInput {
  id: string;
  adminId: string;
  refreshTokenHash: string;
  userAgent?: string | null;
  ipAddress?: string | null;
  expiresAt: Date;
}

export const adminSessionRepository = {
  /** Explicit _id is pre-generated by the caller so it can be embedded in the JWT before the row exists. */
  async create(input: CreateAdminSessionInput): Promise<PlatformAdminSessionDocument> {
    return PlatformAdminSessionModel.create({
      _id: new Types.ObjectId(input.id),
      adminId: input.adminId,
      refreshTokenHash: input.refreshTokenHash,
      userAgent: input.userAgent ?? null,
      ipAddress: input.ipAddress ?? null,
      expiresAt: input.expiresAt,
    });
  },

  /** Includes refreshTokenHash - only for refresh-token verification. */
  async findByIdAndAdminWithHash(id: string, adminId: string): Promise<PlatformAdminSessionDocument | null> {
    if (!Types.ObjectId.isValid(id)) return null;
    return PlatformAdminSessionModel.findOne({ _id: id, adminId }).select('+refreshTokenHash').exec();
  },

  async updateHash(id: string, refreshTokenHash: string, expiresAt: Date): Promise<void> {
    await PlatformAdminSessionModel.updateOne(
      { _id: id },
      { $set: { refreshTokenHash, expiresAt, lastUsedAt: new Date() } },
    ).exec();
  },

  async deleteById(id: string): Promise<void> {
    if (!Types.ObjectId.isValid(id)) return;
    await PlatformAdminSessionModel.deleteOne({ _id: id }).exec();
  },

  async deleteByIdAndAdmin(id: string, adminId: string): Promise<boolean> {
    if (!Types.ObjectId.isValid(id)) return false;
    const result = await PlatformAdminSessionModel.deleteOne({ _id: id, adminId }).exec();
    return result.deletedCount > 0;
  },
};
